=== hugo-allard/master-thesis/code/doc/inputs/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Retirer les productedTransducer car inutile pour les sorties aussi, juste pour test !!!!! -->

<xs:element name="graph" type="graph"/>
<xs:element name="automaton" type="graph"/>
<xs:element name="transducer" type="graph"/>
<xs:element name="productedtransducer" type="graph"/>

	<xs:complexType name="graph">
		<xs:sequence>
			<xs:element name="nodes">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="node" type="node" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="transitions">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="transition" type="transition" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>

		<xs:attribute name="size" type="xs:positiveInteger" use="required"/>
	</xs:complexType>

	<xs:complexType name="node">
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
		<xs:attribute name="initial" type="xs:boolean"/>
		<xs:attribute name="accepting" type="xs:boolean"/>
		<xs:attribute name="output" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="transition">
		<xs:attribute name="from" type="xs:nonNegativeInteger" use="required"/>
		<xs:attribute name="to" type="xs:nonNegativeInteger" use="required"/>
		<xs:attribute name="input" type="xs:string" use="required"/>
		<xs:attribute name="output" type="xs:string"/>
		<xs:attribute name="output2" type="xs:string"/>
	</xs:complexType>		
</xs:schema>

=== hugo-allard/master-thesis/code/doc/inputs/Example10.xml
<?xml version="1.0" encoding="utf-8"?>

<transducer size="4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schema.xsd">

  <!--  figure 3.2 -->
  <nodes>
    <node id="0" initial="true" accepting="true" />
    <node id="1" />
    <node id="2" />
    <node id="3" accepting="true" />
  </nodes>
  
  <transitions>
    <transition from="0" to="1" input="a" output="x" />
    <transition from="0" to="2" input="a" output="xxx" />
    <transition from="1" to="2" input="a" output="xxxx" />
    <transition from="1" to="3" input="a" output="xxx" />
    <transition from="2" to="3" input="a" output="x" />
    <transition from="3" to="0" input="a" output="xx" />
  </transitions>
</transducer>

=== hugo-allard/master-thesis/code/doc/inputs/Example4.xml
<?xml version="1.0" encoding="UTF-8"?>

<transducer size="3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schema.xsd">

  <!--  figure 4.2(b) -->
  <nodes>
    <node id="0" initial="true" />
    <node id="1" accepting="true" />
    <node id="2" />
  </nodes>
  
  <transitions>
    <transition from="0" to="1" input="a" output="x" />
    <transition from="0" to="2" input="a" output="y" />
    <transition from="1" to="2" input="a" output="" />
    <transition from="2" to="1" input="a" output="" />
  </transitions>
</transducer>

=== hugo-allard/master-thesis/code/doc/inputs/Example2.xml
<?xml version="1.0" encoding="UTF-8"?>

<transducer size="3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schema.xsd">

  <nodes>
    <node id="0" initial="true" />
    <node id="1" />
    <node id="2" accepting="true" />
  </nodes>
  
  <transitions>
    <transition from="0" to="1" input="a" output="xx" />
    <transition from="0" to="2" input="a" output="x" />
    <transition from="1" to="2" input="a" output="x" />
    <transition from="2" to="1" input="a" output="x" />
  </transitions>
</transducer>

=== hugo-allard/master-thesis/code/doc/inputs/Example3.xml
<?xml version="1.0" encoding="UTF-8"?>

<transducer size="6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schema.xsd">

  <nodes>
    <node id="0" initial="true" />
    <node id="1" />
    <node id="2" />
    <node id="3" />
    <node id="4" />
    <node id="5" accepting="true" />
  </nodes>
  
  <transitions>
    <transition from="0" to="1" input="x" output="a" />
    <transition from="0" to="2" input="x" output="" />
    <transition from="1" to="3" input="y" output="b" />
    <transition from="1" to="5" input="x" output="b" />
    <transition from="3" to="1" input="y" output="a" />
    <transition from="2" to="4" input="y" output="a" />
    <transition from="2" to="5" input="x" output="a" />
    <transition from="4" to="2" input="y" output="b" />
  </transitions>
</transducer>

=== hugo-allard/master-thesis/code/doc/inputs/Example1.xml
<?xml version="1.0" encoding="utf-8"?>

<transducer size="4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schema.xsd">

  <nodes>
    <node id="0" initial="true" />
    <node id="1" />
    <node id="2" />
    <node id="3" accepting="true" />
  </nodes>
  
  <transitions>
    <transition from="0" to="1" input="a" output="b" />
    <transition from="0" to="2" input="a" output="c" />
    <transition from="1" to="3" input="h" output="h" />
    <transition from="2" to="3" input="e" output="e" />
  </transitions>
</transducer>

=== hugo-allard/master-thesis/code/doc/outputs/out.xml
<?xml version="1.0" ?>
<transducer size="8" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">

  <nodes>
    <node id="0" initial="true" accepting="true"/>
    <node id="1"/>
    <node id="2" accepting="true"/>
    <node id="3" accepting="true"/>
    <node id="4" accepting="true" output="x"/>
    <node id="5" accepting="true" output="x"/>
    <node id="6" accepting="true"/>
    <node id="7" accepting="true" output="x"/>
  </nodes>

  <transitions>
    <transition from="0" to="1" input="a" output="x"/>
    <transition from="1" to="2" input="a" output="xxx"/>
    <transition from="2" to="3" input="a" output="xx"/>
    <transition from="3" to="4" input="a" output="x"/>
    <transition from="4" to="5" input="a" output="xx"/>
    <transition from="5" to="6" input="a" output="xxx"/>
    <transition from="6" to="7" input="a" output="x"/>
    <transition from="7" to="7" input="a" output="xx"/>
  </transitions>
</transducer>

=== hugo-allard/master-thesis/code/doc/inputs/Example8.xml
<?xml version="1.0" encoding="UTF-8"?>

<transducer size="6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schema.xsd">

  <!-- figure 5.1  -->
  <nodes>
    <node id="0" initial="true" />
    <node id="1" />
    <node id="2" />
    <node id="3" />
    <node id="4" accepting="true" />
    <node id="5" accepting="true" />
  </nodes>
  
  <transitions>
    <transition from="0" to="1" input="a" output="b" />
    <transition from="0" to="3" input="a" output="ba" />
    <transition from="1" to="2" input="a" output="" />
    <transition from="2" to="1" input="a" output="" />
    <transition from="2" to="5" input="b" output="ac" />
    <transition from="3" to="4" input="a" output="" />
    <transition from="4" to="3" input="a" output="" />
    <transition from="5" to="5" input="a" output="a" />
  </transitions>
</transducer>
